

services:
  # db:
  #   image: ankane/pgvector
  #   container_name: pgvector-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: fastapi_db
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: fastapi-app
    working_dir: /code
    volumes:
      - ./backend:/code
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --ssl-keyfile /code/certs/key.pem --ssl-certfile /code/certs/cert.pem"
             
    ports:
      - "8000:8000"
    # depends_on:
    #   db:
    #     condition: service_healthy
    env_file:
      - ./backend/.env

 # Optional
  # frontend:
  #   container_name: vue-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   command: npm run dev
  #   working_dir: /app
  #   stdin_open: true
  #   tty: true

volumes:
  pgdata: