

services:
  # db:
  #   image: ankane/pgvector
  #   container_name: pgvector-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: fastapi_db
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-U", "postgres"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: fastapi-app
    working_dir: /code
    volumes:
      - ./backend:/code

    # Activate forwarded allow ips for https redirections
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --forwarded-allow-ips='*'"
    # ports:
    # - "8000:8000"    # Remove in production and only accepts nginx connections
    # depends_on:
    #   db:
    #     condition: service_healthy
    env_file:
      - ./backend/.env
    networks:
      - app-network
  
  # Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./backend/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
    networks:
      - app-network

 # Optional
  # frontend:
  #   container_name: vue-frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #   command: npm run dev
  #   working_dir: /app
  #   stdin_open: true
  #   tty: true

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge