"""create columns of ai for backend

Revision ID: 728c41137127
Revises: 762db67faf05
Create Date: 2025-05-25 13:19:22.674779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728c41137127'
down_revision: Union[str, None] = '762db67faf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('ai_health_summary', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('ai_health_conclusion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'ai_health_conclusion')
    op.drop_column('products', 'ai_health_summary')
    # ### end Alembic commands ###
