"""user model change

Revision ID: 762db67faf05
Revises: 06c64a7244ca
Create Date: 2025-05-22 11:59:46.191373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '762db67faf05'
down_revision: Union[str, None] = '06c64a7244ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('badges', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('badges_name_key'), 'badges', type_='unique')
    op.create_index(op.f('ix_badges_name'), 'badges', ['name'], unique=True)
    op.drop_constraint(op.f('health_flags_name_key'), 'health_flags', type_='unique')
    op.create_index(op.f('ix_health_flags_name'), 'health_flags', ['name'], unique=True)
    op.drop_column('user_badges', 'earned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_badges', sa.Column('earned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_health_flags_name'), table_name='health_flags')
    op.create_unique_constraint(op.f('health_flags_name_key'), 'health_flags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_badges_name'), table_name='badges')
    op.create_unique_constraint(op.f('badges_name_key'), 'badges', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('badges', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
