"""test

Revision ID: 79faedee8307
Revises: 8009bb0af502
Create Date: 2025-05-20 17:30:19.021703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79faedee8307'
down_revision: Union[str, None] = '8009bb0af502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('text_content', sa.String(), nullable=True))
    op.drop_index('ix_user_badges_id', table_name='user_badges')
    op.drop_column('user_badges', 'id')
    op.drop_index('ix_user_health_flags_id', table_name='user_health_flags')
    op.drop_column('user_health_flags', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_health_flags', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_health_flags_id', 'user_health_flags', ['id'], unique=False)
    op.add_column('user_badges', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_badges_id', 'user_badges', ['id'], unique=False)
    op.drop_column('history', 'text_content')
    # ### end Alembic commands ###
