"""delete user_health_flag id

Revision ID: 8009bb0af502
Revises: cdd74cd6093f
Create Date: 2025-05-20 17:20:07.040854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8009bb0af502'
down_revision: Union[str, None] = 'cdd74cd6093f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
