"""health_flag

Revision ID: 9e18b94b6722
Revises: dbf6edb429d5
Create Date: 2025-05-20 13:31:52.591317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e18b94b6722'
down_revision: Union[str, None] = 'dbf6edb429d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_health_flags_id'), 'health_flags', ['id'], unique=False)
    op.create_table('user_health_flags',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('health_flag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['health_flag_id'], ['health_flags.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'health_flag_id', 'id')
    )
    op.create_index(op.f('ix_user_health_flags_id'), 'user_health_flags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_health_flags_id'), table_name='user_health_flags')
    op.drop_table('user_health_flags')
    op.drop_index(op.f('ix_health_flags_id'), table_name='health_flags')
    op.drop_table('health_flags')
    # ### end Alembic commands ###
