"""fix user_health_flags schema

Revision ID: cdd74cd6093f
Revises: 9e18b94b6722
Create Date: 2025-05-20 17:12:14.937972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdd74cd6093f'
down_revision: Union[str, None] = '9e18b94b6722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
